// APP REDUCER
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

// FLIGHTS REDUCER
export const FETCH_FLIGHTS_INIT = 'FETCH_FLIGHTS_INIT';
export const FETCH_FLIGHTS_START = 'FETCH_FLIGHTS_START';
export const FETCH_FLIGHTS_ERROR = 'FETCH_FLIGHTS_ERROR';
export const FETCH_FLIGHTS_SUCESS = 'FETCH_FLIGHTS_SUCESS';
export const TOGGLE_IS_BOOKING_FLIGHT = 'TOGGLE_IS_BOOKING_FLIGHT';
export const SHOW_MORE_FLIGHT_INFO = 'SHOW_MORE_FLIGHT_INFO';
export const RESET_FLIGHT_MODAL_CONTENT = 'RESET_FLIGHT_MODAL_CONTENT';
