// APP
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

// FETCH FLIGHTS
export const FETCH_FLIGHTS_INIT = 'FETCH_FLIGHTS_INIT';
export const FETCH_FLIGHTS_START = 'FETCH_FLIGHTS_START';
export const FETCH_FLIGHTS_ERROR = 'FETCH_FLIGHTS_ERROR';
export const FETCH_FLIGHTS_SUCESS = 'FETCH_FLIGHTS_SUCESS';

// FLIGHT MODALS
export const TOGGLE_IS_BOOKING_FLIGHT = 'TOGGLE_IS_BOOKING_FLIGHT';
export const TOGGLE_FLIGHT_DETAILS = 'TOGGLE_FLIGHT_DETAILS';
